logo: "/images/MyImage.jpg?raw=true"
description: > 
  Passionate about solving complex real-world problems.
  Masters in Applied Mathematics. 
  <br><br>
  Husband, father, brother, son. Omnem gloriam Dei.
  
theme: jekyll-theme-minimal
google_analytics: 199901983 # your Google Analytics tracking ID here

# The "View on GitHub" button
github:
  is_project_page: true

# Custom CSS to override theme styles
sass:
  style: compressed

# Custom CSS
custom_css: |
  .wrapper { max-width: 960px; }
  body { color: #333; }
  a { color: #333; }
  a:hover { color: #000; }
  h1, h2, h3, h4, h5, h6 { color: #333; }
