title: Chris Schmidt
logo: "/images/MyImage.jpg?raw=true"
description: > 
  Applied mathematician with a master's degree in Applied Mathematics.
  Specializing in data analytics, engineering, and scientific computing.
  Passionate about solving complex real-world problems using quantitative analysis.
  <br><br>
  Husband, father, brother, son. Omnem gloriam Dei.
  
theme: jekyll-theme-minimal
google_analytics: 199901983 # your Google Analytics tracking ID here

# Hide the "View on GitHub" button
github:
  is_project_page: false

# Remove the "Hosted on GitHub Pages" text
footer:
  hide: true
