title: Chris Schmidt
logo: "/images/me3.jpg?raw=true"
description: > 
  Applied mathematician with a master's degree, focusing on data analytics, engineering, and science.
  Passionate about leveraging mathematical skills to solve real-world problems.
  <br><br>
  Husband, father, brother, son. Omnem gloriam Dei.
  <br><br>
  <a href="https://www.linkedin.com/in/chris-schmidt-94526a10/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 199901983 # your Google Analytics tracking ID here
